# PowerShell Skills Smoke Test
# Run this in Windows PowerShell to verify commands parse correctly
# Generated by eval-skills-rigorous.py

$Results = @()

# --- powershell-master ---
try {
    Get-Command -Name 'Get-ChildItem' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-ChildItem'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-ChildItem'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-Process' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-Process'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-Process'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-Service' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-Service'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Get-Service'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Test-Connection' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Test-Connection'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Test-Connection'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Select-Object' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Select-Object'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Select-Object'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Where-Object' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Where-Object'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-master'
        Cmdlet = 'Where-Object'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

# --- powershell-security ---
try {
    Get-Command -Name 'Get-MpPreference' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Get-MpPreference'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Get-MpPreference'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-ExecutionPolicy' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Get-ExecutionPolicy'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Get-ExecutionPolicy'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Set-MpPreference' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Set-MpPreference'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-security'
        Cmdlet = 'Set-MpPreference'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

# --- powershell-7.5-features ---
try {
    Get-Command -Name 'Get-Module' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'Get-Module'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'Get-Module'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-Command' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'Get-Command'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'Get-Command'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'ConvertTo-CliXml' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'ConvertTo-CliXml'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-7.5-features'
        Cmdlet = 'ConvertTo-CliXml'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

# --- win11-admin ---
try {
    Get-Command -Name 'Get-LocalUser' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-LocalUser'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-LocalUser'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-ScheduledTask' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-ScheduledTask'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-ScheduledTask'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-NetFirewallProfile' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-NetFirewallProfile'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-NetFirewallProfile'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-BitLockerVolume' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-BitLockerVolume'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'win11-admin'
        Cmdlet = 'Get-BitLockerVolume'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

# --- powershell-shell-detection ---
try {
    Get-Command -Name 'Get-ChildItem' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-shell-detection'
        Cmdlet = 'Get-ChildItem'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-shell-detection'
        Cmdlet = 'Get-ChildItem'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}

try {
    Get-Command -Name 'Get-Process' -ErrorAction Stop | Out-Null
    $Results += [PSCustomObject]@{
        Skill = 'powershell-shell-detection'
        Cmdlet = 'Get-Process'
        Status = 'Available'
    }
} catch {
    $Results += [PSCustomObject]@{
        Skill = 'powershell-shell-detection'
        Cmdlet = 'Get-Process'
        Status = 'MISSING: ' + $_.Exception.Message
    }
}


# Summary
$Results | Format-Table -AutoSize
$Results | Group-Object Status | Select-Object Name, Count
